/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MaiCoin } from './MaiCoin.js';
export * as factories from './factories/index.js';
export { MaiCoin__factory } from './factories/MaiCoin__factory.js';